package com.soften.ltp.model;

public class EmotionWord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_word.uuid
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_word.word
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_word.word_type
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    private String wordType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_word.word_sense_count
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    private Integer wordSenseCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_word.word_sense_order
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    private Integer wordSenseOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_word.emotion_type
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    private String emotionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_word.strength
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    private Integer strength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_word.polarity
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    private Integer polarity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_word.auxiliarye_emotion
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    private String auxiliaryeEmotion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_word.auxiliarye_strenth
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    private Integer auxiliaryeStrenth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_word.auxiliarye_polarity
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    private Integer auxiliaryePolarity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emotion_word.feature
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    private Integer feature;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_word.uuid
     *
     * @return the value of emotion_word.uuid
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_word.uuid
     *
     * @param uuid the value for emotion_word.uuid
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_word.word
     *
     * @return the value of emotion_word.word
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_word.word
     *
     * @param word the value for emotion_word.word
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_word.word_type
     *
     * @return the value of emotion_word.word_type
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public String getWordType() {
        return wordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_word.word_type
     *
     * @param wordType the value for emotion_word.word_type
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public void setWordType(String wordType) {
        this.wordType = wordType == null ? null : wordType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_word.word_sense_count
     *
     * @return the value of emotion_word.word_sense_count
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public Integer getWordSenseCount() {
        return wordSenseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_word.word_sense_count
     *
     * @param wordSenseCount the value for emotion_word.word_sense_count
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public void setWordSenseCount(Integer wordSenseCount) {
        this.wordSenseCount = wordSenseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_word.word_sense_order
     *
     * @return the value of emotion_word.word_sense_order
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public Integer getWordSenseOrder() {
        return wordSenseOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_word.word_sense_order
     *
     * @param wordSenseOrder the value for emotion_word.word_sense_order
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public void setWordSenseOrder(Integer wordSenseOrder) {
        this.wordSenseOrder = wordSenseOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_word.emotion_type
     *
     * @return the value of emotion_word.emotion_type
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public String getEmotionType() {
        return emotionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_word.emotion_type
     *
     * @param emotionType the value for emotion_word.emotion_type
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public void setEmotionType(String emotionType) {
        this.emotionType = emotionType == null ? null : emotionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_word.strength
     *
     * @return the value of emotion_word.strength
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public Integer getStrength() {
        return strength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_word.strength
     *
     * @param strength the value for emotion_word.strength
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public void setStrength(Integer strength) {
        this.strength = strength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_word.polarity
     *
     * @return the value of emotion_word.polarity
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public Integer getPolarity() {
        return polarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_word.polarity
     *
     * @param polarity the value for emotion_word.polarity
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public void setPolarity(Integer polarity) {
        this.polarity = polarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_word.auxiliarye_emotion
     *
     * @return the value of emotion_word.auxiliarye_emotion
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public String getAuxiliaryeEmotion() {
        return auxiliaryeEmotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_word.auxiliarye_emotion
     *
     * @param auxiliaryeEmotion the value for emotion_word.auxiliarye_emotion
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public void setAuxiliaryeEmotion(String auxiliaryeEmotion) {
        this.auxiliaryeEmotion = auxiliaryeEmotion == null ? null : auxiliaryeEmotion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_word.auxiliarye_strenth
     *
     * @return the value of emotion_word.auxiliarye_strenth
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public Integer getAuxiliaryeStrenth() {
        return auxiliaryeStrenth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_word.auxiliarye_strenth
     *
     * @param auxiliaryeStrenth the value for emotion_word.auxiliarye_strenth
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public void setAuxiliaryeStrenth(Integer auxiliaryeStrenth) {
        this.auxiliaryeStrenth = auxiliaryeStrenth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_word.auxiliarye_polarity
     *
     * @return the value of emotion_word.auxiliarye_polarity
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public Integer getAuxiliaryePolarity() {
        return auxiliaryePolarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_word.auxiliarye_polarity
     *
     * @param auxiliaryePolarity the value for emotion_word.auxiliarye_polarity
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public void setAuxiliaryePolarity(Integer auxiliaryePolarity) {
        this.auxiliaryePolarity = auxiliaryePolarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emotion_word.feature
     *
     * @return the value of emotion_word.feature
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public Integer getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emotion_word.feature
     *
     * @param feature the value for emotion_word.feature
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    public void setFeature(Integer feature) {
        this.feature = feature;
    }
}