package com.soften.ltp.model;

public class SentenceEmotion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_emotion.uuid
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_emotion.sentence
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    private String sentence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_emotion.sentence_words
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    private String sentenceWords;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_emotion.uuid
     *
     * @return the value of sentence_emotion.uuid
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_emotion.uuid
     *
     * @param uuid the value for sentence_emotion.uuid
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_emotion.sentence
     *
     * @return the value of sentence_emotion.sentence
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    public String getSentence() {
        return sentence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_emotion.sentence
     *
     * @param sentence the value for sentence_emotion.sentence
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    public void setSentence(String sentence) {
        this.sentence = sentence == null ? null : sentence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_emotion.sentence_words
     *
     * @return the value of sentence_emotion.sentence_words
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    public String getSentenceWords() {
        return sentenceWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_emotion.sentence_words
     *
     * @param sentenceWords the value for sentence_emotion.sentence_words
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    public void setSentenceWords(String sentenceWords) {
        this.sentenceWords = sentenceWords == null ? null : sentenceWords.trim();
    }
}