package com.soften.ltp.mapper;

import com.soften.ltp.model.EmotionWord;
import com.soften.ltp.model.EmotionWordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmotionWordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_word
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    int countByExample(EmotionWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_word
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    int deleteByExample(EmotionWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_word
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_word
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    int insert(EmotionWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_word
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    int insertSelective(EmotionWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_word
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    List<EmotionWord> selectByExample(EmotionWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_word
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    EmotionWord selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_word
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") EmotionWord record, @Param("example") EmotionWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_word
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    int updateByExample(@Param("record") EmotionWord record, @Param("example") EmotionWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_word
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    int updateByPrimaryKeySelective(EmotionWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion_word
     *
     * @mbggenerated Tue Mar 10 14:05:36 CST 2015
     */
    int updateByPrimaryKey(EmotionWord record);
}