package com.soften.ltp.mapper;

import com.soften.ltp.model.SentenceEmotion;
import com.soften.ltp.model.SentenceEmotionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SentenceEmotionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_emotion
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    int countByExample(SentenceEmotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_emotion
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    int deleteByExample(SentenceEmotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_emotion
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_emotion
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    int insert(SentenceEmotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_emotion
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    int insertSelective(SentenceEmotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_emotion
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    List<SentenceEmotion> selectByExample(SentenceEmotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_emotion
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    SentenceEmotion selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_emotion
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    int updateByExampleSelective(@Param("record") SentenceEmotion record, @Param("example") SentenceEmotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_emotion
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    int updateByExample(@Param("record") SentenceEmotion record, @Param("example") SentenceEmotionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_emotion
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    int updateByPrimaryKeySelective(SentenceEmotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_emotion
     *
     * @mbggenerated Mon Mar 09 13:41:29 CST 2015
     */
    int updateByPrimaryKey(SentenceEmotion record);
}